# Generated by Django 5.2.8 on 2025-11-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('maker', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='available', max_length=50)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(max_length=255)),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('performed_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_movements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'asset_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComputerSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'computer_specs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size_inch', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'monitor_specs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrinterSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_color', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'printer_specs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScannerSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dpi', models.IntegerField(blank=True, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'scanner_specs',
                'managed': False,
            },
        ),
    ]
